### ISSUE TITLE
Can add me please?

### ISSUE THREAD

**Issue by FancyFear** [kodi-connect/kodi-alexa-video#10]
Hi, can you add my Amazon Account to this awsome Skill? (magixbox@gmx.de)
THX :)

**Comment by tkislan** [comment]
I've added you.
Here's the [link](https://skills-store.amazon.com/deeplink/tvt/afacb1fdc71a76b0a3be13de60a7240d0b110ec80de8ef7aff379ab9e55ae351de9ff779708481764fb95e4116977c65288c0a0d4e0d4581444d002626f1bca3a76881226d04b4289b89bc2c1fcaea674fa0bc00b764d51613f43cea57cd871c5fed97221e35ffe6bc19dd9292f311cf) to enable the skill.
You can also remove your email from the comment.
