### ISSUE TITLE
Can't download addon

### ISSUE THREAD

**Issue by chest069** [kodi-connect/kodi-alexa-video#11]
Hello,
I am trying to download the add-on so that I can install it in Kodi but when I click the link it is for a read.md file not a zip file for kodi. I did try to also download the zip file on git hub and that wouldn't work either. Can you help me out in this.

**Comment by tkislan** [comment]
Hey. What link are you using to download the addon? And where did you find it?

**Comment by chest069** [comment]
Sorry about that.
https://github.com/kodi-connect/kodi-alexa-video is the page I started on.
https://github.com/kodi-connect/kodi-connect-addon/blob/master/tutorial/readme.md is the file I grab.
and also
https://github.com/kodi-connect/kodi-connect-addon is where I try to get the kodi addon and install it but kodi doesn't accept it or let me install it.
Thanks for the reply

**Comment by chest069** [comment]
OK, so that link enabled me to download the Kodi Connect Add-on and install it.
I have it running on Kodi now I just need to test it and see how it works with my Alexa.
Thanks for the help.
