### ISSUE TITLE
Can't download Skill from Amazon

### ISSUE THREAD

**Issue by chest069** [kodi-connect/kodi-alexa-video#12]
Hello,
I am following the tutorial and have gotten to the point to where I am supposed to download and install and enable the Skill from Amazon.
When I search for it nothing comes up what am I doing wrong or missing. This is the part I am at "Next step is enabling Kodi Video Skill on your Alexa See installation steps https://github.com/kodi-connect/kodi-alexa-video/blob/master/tutorial/readme.md"
Any help would be great. Thanks.

**Comment by tkislan** [comment]
https://github.com/kodi-connect/kodi-alexa-video/blob/master/readme.md#beta-testing

**Comment by chest069** [comment]
I'm sorry my email is chest069@gmail.com I thought when I did the part where it gave me the secret key that was enough. I apologize.

**Comment by tkislan** [comment]
No problem. I've added you.
Here's the [link](https://skills-store.amazon.com/deeplink/tvt/afacb1fdc71a76b0a3be13de60a7240d0b110ec80de8ef7aff379ab9e55ae351de9ff779708481764fb95e4116977c65288c0a0d4e0d4581444d002626f1bca3a76881226d04b4289b89bc2c1fcaea674fa0bc00b764d51613f43cea57cd871c5fed97221e35ffe6bc19dd9292f311cf) to enable the skill.
You can also remove your email from the comment

**Comment by chest069** [comment]
Thanks
