### ISSUE TITLE
Can you add me please?

### ISSUE THREAD

**Issue by dersch81** [kodi-connect/kodi-alexa-video#15]
Would be great. Is German control possible? send you a PM

**Comment by tkislan** [comment]
Yes, German should be supported (even though I didn't test it myself).
Did you receive an invitation? As I don't know where and how you've PMed me

**Comment by dersch81** [comment]
Hi, so I finally installed the Kodi Plugin (i'm running 17.6) and connected to your server. Then i could discover the Kodi Device within the Alexa App. I choosed the echo devices to control. But nothing happens if i ask for play, stop, pause etc.

**Comment by tkislan** [comment]
Yes, there is a plan for the future, I just need to find some free time to get it done.
