### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by zercool524** [kodi-connect/kodi-alexa-video#17]
Does this only work with Alexa Echo or can it work with Amazon Fire TV with Alexa voice remote because I have everything installed far as I know it's not giving me an error no connection to disconnection to connection it says connected did I miss a step along the way installed everything followed each picture on how to do it is there something to where I have to be added to something to see it in the Alexa website as a skill because that is the only thing that I couldn't do because I didn't see the Kodi video thing to add as a skill thanks very much hope they get this figured out have a good day

**Comment by chest069** [comment]
I am also having this problem. I have a Amazon Fire Cube Tv and was beta testing it on the echo dot before and didn't have this issue. Any thoughts or ideas, I get the error about needing to install home connect but I don't see a way to enable that.

**Comment by tkislan** [comment]
Yes, multiple people are reporting this issue, that if they're using Alexa through Fire TV, she forwards the requests straight to Prime TV. Unfortunately, I can't do anything about this, because Alexa is the one, that decides what to do with the request.

**Comment by zercool524** [comment]
I'm going to get an Alexa Echo and from videos I've watched it should work but with the Fire TV Alexa remote does not work because it doesn't recognize it as a Alexa Echo maybe in the future it could be compatible with the Fire TV that would allow you to install it like you would install Kodi or some other type of app that's not on the App Store

**Comment by tkislan** [comment]
This is something you need to address to Amazon.
