### ISSUE TITLE
No kodi visible

### ISSUE THREAD

**Issue by pratikkhandelwal** [kodi-connect/kodi-alexa-video#19]
Its does not show any kodi, have tried multiple times but is not visible .
It shows Alexa is looking for devices and then no devices are visible and screen turns black.

**Comment by tkislan** [comment]
And does the kodi connect addon connects? Do you get the `Connected` notification?

**Comment by pratikkhandelwal** [comment]
How do i install addon in my kodi running on raspberrypi?

**Comment by tkislan** [comment]
I'm sure you'll be able to find answers to this with the help of Google

**Comment by tkislan** [comment]
@pratikkhandelwal Black screen is cause by not having supported Content country set up within your Amazon account

**Comment by pratikkhandelwal** [comment]
When will the official skill be awailable?

**Comment by tkislan** [comment]
Not sure. But even then, the requirement for the Content country would be the same ...
