### ISSUE TITLE
Followed instructions but no skill

### ISSUE THREAD

**Issue by andrewvint** [kodi-connect/kodi-alexa-video#20]
Hi,

I have setup and installed everything as per the instructions, however when I go to the Alexa app and select ‘your skill’ I can’t see the kodi video skill even under the dev section.

Am I doing something wrong ?

**Comment by tkislan** [comment]
And did you message me with your Amazon/Alexa email? So that I can add you to the list of beta testers?

**Comment by andrewvint** [comment]
Hi,

I registered on your website, didn’t realise there was an additional step.

If you can add my email address to the beta testing programme that would be great.

Andrew.vint@vintnet.com

**Comment by tkislan** [comment]
Okay, I've added you.
Here is the link to access the skill:
https://skills-store.amazon.com/deeplink/tvt/35ed769718fa7844ca815bad3bcbdc4533f473bc8cba1c56debee36f45ad02df986a5a0596090569b5352dd814d1e3cde3db1da0d8719269aacfec72269f1157f19b57b1f15a006fc1fd56b2b2b9e8a0fe239878e0a8e038e1172e140eace7a62661cae0a299650473e8b33bd604d1ee

**Comment by andrewvint** [comment]
Thank you ☺
