### ISSUE TITLE
Add me please?

### ISSUE THREAD

**Issue by bfenty** [kodi-connect/kodi-alexa-video#21]
Bfenty@gmail

**Comment by bfenty** [comment]
please?

**Comment by tkislan** [comment]
I've added you, and here is the link to activate the skill:
https://skills-store.amazon.com/deeplink/tvt/35ed769718fa7844ca815bad3bcbdc4533f473bc8cba1c56debee36f45ad02df986a5a0596090569b5352dd814d1e3cde3db1da0d8719269aacfec72269f1157f19b57b1f15a006fc1fd56b2b2b9e8a0fe239878e0a8e038e1172e140eace7a62661cae0a299650473e8b33bd604d1ee

**Comment by bfenty** [comment]
Thank you very much!

**Comment by bfenty** [comment]
Just wanted to come back and say this is an awesome skill. Thank you for creating it!
