### ISSUE TITLE
Plase add me

### ISSUE THREAD

**Issue by tn1sz** [kodi-connect/kodi-alexa-video#24]
Hi I am willing to try this skill, please add the account trustno1sz at gmail

thanks in advance
Sheldon

**Comment by tkislan** [comment]
Hi, I've added you.

[You can enable the skill here](https://skills-store.amazon.com/deeplink/tvt/35ed769718fa7844ca815bad3bcbdc4533f473bc8cba1c56debee36f45ad02df986a5a0596090569b5352dd814d1e3cde3db1da0d8719269aacfec72269f1157f19b57b1f15a006fc1fd56b2b2b9e8a0fe239878e0a8e038e1172e140eace7a62661cae0a299650473e8b33bd604d1ee)

**Comment by tn1sz** [comment]
Thanks a lot

**Comment by cutters77** [comment]
Please could you add me gavinsealey53@gmail.com thanks in advance
