### ISSUE TITLE
please add me 

### ISSUE THREAD

**Issue by Maxvb2000** [kodi-connect/kodi-alexa-video#29]
maxvbhaase@web.de

**Comment by tkislan** [comment]
Hey, I've added you, and you can enable the skill here:
https://skills-store.amazon.com/deeplink/tvt/24a62e2c02167c1cbaf1587f715732bedb54bbed63848ce69ad37eb334f72015ebcad8024937de29263c71425d5e31e685dad95afd22e076daafb6cdd5ea25240b9b7d7f5d5192b89c3344fc4b93957635ec91ab05c964920840b9fb6755bf704d787a4b5a02465ad012fcff80a46601
But I had to create a new skill, as the old one has hit the limit of beta testers.
Please confirm, that this skill works as well
