### ISSUE TITLE
Please add me

### ISSUE THREAD

**Issue by peterthorpe81** [kodi-connect/kodi-alexa-video#39]
Please add me to the beta testers. peterthorpe81@googlemail.com

**Comment by piyush25** [comment]
Hi, could you please add me too? Email: crzypiyush.don25@gmail.com
Thanks

**Comment by Lxtxs** [comment]
Please add me to Beta Alexa skill.
Lxtxs@arcor.de

**Comment by Lxtxs** [comment]
Thx

**Comment by Mahalo1218** [comment]
can you please add me to the beta 

gq1977jrm@yahoo.com

**Comment by krasatos** [comment]
Hey, could i please be added to the beta too? i have sent you an email directly. 
Thank you

**Comment by tkislan** [comment]
I've added all the emails here:
[Link](https://skills-store.amazon.com/deeplink/tvt/24a62e2c02167c1cbaf1587f715732bedb54bbed63848ce69ad37eb334f72015ebcad8024937de29263c71425d5e31e685dad95afd22e076daafb6cdd5ea25240b9b7d7f5d5192b89c3344fc4b93957635ec91ab05c964920840b9fb6755bf704d787a4b5a02465ad012fcff80a46601) for Alexa skill
