### ISSUE TITLE
New user

### ISSUE THREAD

**Issue by Mickelin01** [kodi-connect/kodi-alexa-video#4]
Hi Tomas,
Please include me in the beta test. I have registered on the kodiconnect site and installed the add-on, just waiting for the skill in my Alexa app.

I have been struggling all day to install the other Kodi-Alexa skill (m0ngr31) but no luck. Found your new skill while looking for solutions. This seems soo much easier! Really stoked to give it a try, have three Kodis and three Echo Dots around the house.
Thanks

**Comment by tkislan** [comment]
Hi there,

just PM me with your Alexa connected email (either on kodi forums, or reddit, or email)

**Comment by Mickelin01** [comment]
Great, email sent to your gmail
