### ISSUE TITLE
Skill not visible or do you need to add me?

### ISSUE THREAD

**Issue by anglosid** [kodi-connect/kodi-alexa-video#41]
Hi, 

I've done all that;s in the manual (create account on Kodi Connect Server, install Kodi Connect Addon on your Kodi instance) but enabling Kodi Video Skill on my Alexa doesn't show the Kodi skill. My content is set to USA in Amazon. Did I forgot something?

My email: siddy@xs4all.nl

S!d

**Comment by tkislan** [comment]
Already added
