### ISSUE TITLE
Kindly add me to the Beta testers

### ISSUE THREAD

**Issue by Anqit1988** [kodi-connect/kodi-alexa-video#42]
Kindly add my amazon alexa account for the beta testers group. My alexa email address is er.anqitgupta@gmail.com

**Comment by tkislan** [comment]
Added

**Comment by Anqit1988** [comment]
Dear Tomas,

Thank you for adding me to the beta testers group. As instructed by you, I
have configured my Alexa . But still I am unable to access the Kodi Skill
in the skills section of Alexa App. Kindly bear with me and help me out
with this.


Regards,
Ankit Gupta
M.no:- +919910562224
