### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by blacktrails** [kodi-connect/kodi-alexa-video#52]
I have installed the correct repository and addon, and entered my credentials, but every time I try to link my echo with the device Amazon returns "Sorry, we could not find any devices to link." I had one of my Kodis connected but I can get any others to work.

**Comment by tkislan** [comment]
And do you get a "Connected" notification on your Kodi?

**Comment by blacktrails** [comment]
I have gotten this to work on both of my fireTVs. The issues I seem to be having is with Kodi on Xbox one. The addon will not connect to the server. Every time I try, it immediately disconnects. I have retyped the email and secret multiple times.

**Comment by blacktrails** [comment]
Ok why is this closed? Issue isn’t resolved

**Comment by tkislan** [comment]
As per Xbox .. I've just recently discovered, that Xbox is running apps in a sandbox, which prevents use of one of the core libraries (event loop and networking)
So I guess it won't be supported any time soon. I'm sorry about that
