### ISSUE TITLE
Playback for mp3 files?

### ISSUE THREAD

**Issue by 0PK** [kodi-connect/kodi-alexa-video#54]
What a brilliant piece of work, thank you!
I would like to use it to play my mp3 collection on Kodi aswel as playing some Internet radio. Would that be possible if configured in Kodi? Is that something you could possibly consider for the future?

**Comment by tkislan** [comment]
Yes, I have it in my TODO list, I just don't have that much free time anymore.
https://developer.amazon.com/docs/music-skills/api-reference-overview.html
