### ISSUE TITLE
Error During skill setup within Alexa app

### ISSUE THREAD

**Issue by Lif3styl3** [kodi-connect/kodi-alexa-video#58]
Hi,

After Linking kodi with Alexa device nothing Happens.

The Alexa App still Shows no Service connected within Setup.

**Comment by tkislan** [comment]
But does it work if you request to play something?
There is stated in the tutorial, that Alexa app has a bug, and doesn't show any linked devices ...

**Comment by Lif3styl3** [comment]
No, it does mit work. Alexa teils me there is no Video Skill Activated. The skill i have activatesd is Named kodi. Is there a specific kodi video skill ?

**Comment by tkislan** [comment]
What content country do you have set up in your Amazon account?

**Comment by Lif3styl3** [comment]
Hi, 
i've checkd multiple devices.
It does not work on iphone xr and huawei p20.
On my old Galaxy Tab 10.1 2017 Edition it is working fine.

is it possible, that video skills are not supported on mobile devices ?

**Comment by keithputt** [comment]
I was also having the same issue as described.  On restarting Kodi device was discoved

**Comment by broyuken** [comment]
Still having the same issue on my end. Fire stick, skill is enabled, I liked it even though it shows no devices link but I still can’t control anything.

**Comment by trevoroq** [comment]
I had the same problem, I had to uninstall the plug in without deleting the data ( email and secret ) then reinstalled and it appeared in Alexa app.

**Comment by broyuken** [comment]
Having a similar issue, it shows up in the app, I link it to an echo(even though it doesn't show any linked in the app or on the site), but it doesn't play anything or respond to any alexa request.

**Comment by trevoroq** [comment]
After doing the reinstall ,mine now works well, it does disconnect and reconnect quite frequently when I start but then settles down and once connected is ok

**Comment by tkislan** [comment]
@trevoroq That might be caused by unstable internet connection or something similar.
I will try to suppress disconnect notification unless there is really a problem connecting to the server

**Comment by trevoroq** [comment]
Thanks Tomas, I have tried reinstalling with a new secret but still the same, I have it working on 2 Firesticks and a Rockchip H96 Android box, the disconnect reconnect is the only problem, thanks
