### ISSUE TITLE
Music support 

### ISSUE THREAD

**Issue by arigit** [kodi-connect/kodi-alexa-video#6]
Can music playback be supported?
e.g. - shuffle music by genre (alexa shuffle jazz music in kodi), or by band or composer (alexa play some bach in kodi).

Not sure if the this skill would be limited to video-only content hence it's name but thought I would ask. I use kodi for video, but I don't use the video library. I do have my music collection in the kodi library though.

**Comment by tkislan** [comment]
Currently only this (https://github.com/m0ngr31/kanzi) skill supports this.
But at this moment, there is no support for smart music skill (as something similar to Spotify). Maybe in the future Amazon will open this API as well.
