### ISSUE TITLE
Receiving error message from Alexa

### ISSUE THREAD

**Issue by GRClark** [kodi-connect/kodi-alexa-video#60]
She says, “There was a problem with the requested skill’s response.”

**Comment by tkislan** [comment]
And what are you asking when she replies this?

**Comment by GRClark** [comment]
Ask Kodi to play

**Comment by tkislan** [comment]
That is not how you interact with the skill. I did not anticipate this. 
But fair point, I've created an issue here: https://github.com/kodi-connect/kodi-connect-addon/issues/18
As it should be fixed there
