### ISSUE TITLE
I am in Canada with amazon.ca account

### ISSUE THREAD

**Issue by siccnessca** [kodi-connect/kodi-alexa-video#61]
What do I need to do to make this work? I have followed all the steps and upon enabling skill in alexa app, I get no devices discovered. Alexa just searches in firetv not kodi. Using fireTV stick with kodi 17.6 installed.

**Comment by tkislan** [comment]
Amazon made video skills available only in US/UK/DE .. if you want to use it, you need to change content country settings in your Amazon account (not Alexa account)
