### ISSUE TITLE
Turn Off the light after particular interval of time

### ISSUE THREAD

**Issue by Anqit1988** [kodi-connect/kodi-alexa-video#63]
Hi everybody,

I have installed Tasmota on my ESP 8266 and I am writing a rule to turn off my light after particular interval of time after I manually turn it ON. I have tried some of the rules but unable to do so. The rule I am currently trying is:
rule1 on button1#state=1 do backlog power1 1; RuleTimer1 20 endon on Rules#Timer=1 do power1 off endon

I have created a GPIO button on pin D5 (button 1) as well to my light so that I can manually turn ON/OFF my light as well and i have selected D7 as relay 1 to turn ON/OFF my light through the interface. I am confused as to what rule to write so that my light automatically turns OFF after certain interval of time when I manually turn ON the light. 

Thanks in advance.

**Comment by tkislan** [comment]
How is this related to this repository?
