### ISSUE TITLE
Run the timer in loop

### ISSUE THREAD

**Issue by Anqit1988** [kodi-connect/kodi-alexa-video#66]
Hi everyone,

Requesting your help here for a small project i am doing. Basically, I want to Switch On a led connected to one of the GPIO's of my Wemos D1 Mini for 2 or 3 seconds and in a perpetual loop of 5 mins. So every 5 minutes my LEd is ON for 2 seconds and then  OFF and cycle repeats every 5 mins. I am using Tasmota ver 6.3.0. as my firmware.  I have configured to use my module as "Generic" and connected to one of the Digital pins on the D1 mini. I tried using rules but i think i am not using right commands here.

Thanks

**Comment by tkislan** [comment]
How is this related to this repository?
