### ISSUE TITLE
skill not available for English-CA

### ISSUE THREAD

**Issue by drizzt09** [kodi-connect/kodi-alexa-video#7]
please release this for English-CA

**Comment by tkislan** [comment]
Currently it's only officially supported in these 3 countries.
But you can change your content country on Amazon. I don't live in either of those countries, and I'm able to use everything.

<img width="224" alt="screen shot 2018-05-07 at 14 14 42" src="https://user-images.githubusercontent.com/5370798/39701330-0dc8ac68-5201-11e8-85be-83a01707cf7c.png">

**Comment by drizzt09** [comment]
Thank you. Can you keep an eye on when this type of skill is released to English-CA (going to guess India will go at the same time, they seem to usually go hand in hand for late release).
I do not want to switch to anything but English-CA because if I do i lose support for another skill thats only available for English-CA
