### ISSUE TITLE
Request for access

### ISSUE THREAD

**Issue by richkettlewell** [kodi-connect/kodi-alexa-video#8]
Hi can I get access to the skill please?

It looks awesome, nice work!

Email: rich _ kettlewell at hotmail dot com

**Comment by tkislan** [comment]
Hey. I've added you.
Here is the link for the skill:
https://skills-store.amazon.com/deeplink/tvt/afacb1fdc71a76b0a3be13de60a7240d0b110ec80de8ef7aff379ab9e55ae351de9ff779708481764fb95e4116977c65288c0a0d4e0d4581444d002626f1bca3a76881226d04b4289b89bc2c1fcaea674fa0bc00b764d51613f43cea57cd871c5fed97221e35ffe6bc19dd9292f311cf
